version: "3.8"

services:
  fast-api-docker-poetry:
    image: local/fast-api-docker-poetry:${BUILD_TAG:-local-dev}
    ports:
      - "8009:8009"
    build:
      context: .
      dockerfile: Dockerfile
      target: ${TARGET:-test}
    environment:
      POSTGRES_DB_HOST: postgresql
      OTEL_SERVICE_NAME: fastApiDockerPoetry
      OTEL_METRICS_EXPORTER: none
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
    volumes:
      - ./app:/home/appuser/app
      - ./tests:/home/appuser/tests
    depends_on:
      - fast-api-postgres
    links:
      - fast-api-postgres:postgresql

  fast-api-postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
#    volumes:
#      - .pgdata/:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fastapi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres





