version: "3.8"

services:
  fast-api-docker-poetry:
    env_file: local-dev.env
    ports:
      - "8009:8009"

  fast-api-postgres:
    ports:
      - "5432:5432"
    volumes:
      - .pgdata/:/var/lib/postgresql/data
