name: Run tests

on:
  push:
    branches:
      - '*'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check if tag exists
        id: check_tag
        run: |
          if docker pull $IMAGE_NAME; then
            echo "::set-output name=tag_exists::true"
          else
            echo "::set-output name=tag_exists::false"
          fi
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USER }}/fast-api-server:${{ hashFiles('**/Dockerfile') }}${{ hashFiles('**/poetry.lock') }}

      - name: Build and push
        if: steps.check_tag.outputs.tag_exists != 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USER }}/fast-api-server:${{ hashFiles('**/Dockerfile') }}${{ hashFiles('**/poetry.lock') }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USER }}/fast-api-server
          cache-to: type=registry,mode=max,ref=${{ secrets.DOCKER_USER }}/fast-api-server
          target: development

# used for local runner "act"
#      - name: Install Docker Compose
#        run: |
#          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" \
#              -o /usr/local/bin/docker-compose
#          sudo chmod +x /usr/local/bin/docker-compose

      - name: Run tests
        run: |
          docker-compose run --rm fast-api-docker-poetry poetry run pytest -v --durations=10 --durations-min=0.5
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USER }}/fast-api-server:${{ hashFiles('**/Dockerfile') }}${{ hashFiles('**/poetry.lock') }}

